### ISSUE TITLE
Undefined

### ISSUE THREAD

**Issue by alexlazk** [danieldeng2/perlego-downloader#1]
When I hit enter at the Chrome console, it returns "undefined" and didn't execute the code

**Comment by danieldeng2** [comment]
My free trial is over so I can't verify the problem. Are you using `PerlegoOutline.js`?

**Comment by alexlazk** [comment]
![2021-01-09 13_01_08-Microsoft Store](https://user-images.githubusercontent.com/36182444/104106388-039ce100-527b-11eb-8ebe-22bdc3cf106b.png)
Here's a screenshot

**Comment by danieldeng2** [comment]
That's expected behaviour, you need to then run type `printPages(startPage, endPage)` into the console. e.g. `printPages(1, 5)`. 
Also that wouldn't work for this book just yet as it only support books that are uploaded as pdfs for now. read the readme.

**Comment by alexlazk** [comment]
Thanks!
