### ISSUE TITLE
Images not loading

### ISSUE THREAD

**Issue by dd20201** [danieldeng2/perlego-downloader#15]
Hello, 
I'm asking for an urgent help as the images are not loading. I have tried with different timeout settings, but with no solution. Although there is no problem with the loading of the front cover. Not a single image of the book is loading. Any help will be highly appreciated.

**Comment by dd20201** [comment]
Kindly let me know if there is any solution. I can download the entire book, but without any image. Could you please what might be the source of the problem? The books I'm seeking kind of instructor's manual, thus the images are very important.

**Comment by danieldeng2** [comment]
Should be fixed. Try again.
