### ISSUE TITLE
Image not loading when the book isn't divided chapterwise

### ISSUE THREAD

**Issue by dd20201** [danieldeng2/perlego-downloader#16]
First of all, thanks a lot for resolving the previous image issue. It's working perfectly fine for the ebooks which are chapterwise divided. But unfortunately for the ebooks which are not divided chapterwise (i.e, that can be scrolled down continuously till the end), the images are not being loaded. If you can kindly check the case and resolve the issue as always, it'd be enormously helpful. 
As an example - https://ereader.perlego.com/1/book/394710/22

**Comment by danieldeng2** [comment]
Try the latest version. It should be a browser caching issue
