### ISSUE TITLE
WebSocket is already in CLOSING or CLOSED state.

### ISSUE THREAD

**Issue by thelordteuz** [danieldeng2/perlego-downloader#17]
Hi,
The script works great but with some ebooks when it is in the "loading" phase I get this message and there is nothing I can do to save the book. 
What can I do? 
Thanks!!!
<img width="545" alt="Perlego Error" src="https://user-images.githubusercontent.com/89242984/130473058-4ac39164-7ddc-424b-af86-ca33445c0ac0.png">

**Comment by danieldeng2** [comment]
20000 means 20 seconds to load each page, consider using a lower number

websockets is not the script's fault
