### ISSUE TITLE
text misaligned with image in PDF

### ISSUE THREAD

**Issue by otichy** [danieldeng2/perlego-downloader#18]
I downloaded an apparently OCRed PDF, it worked great, but the OCRed text is rendered as a visible text layer above the image. The text is misaligned with the image making the PDF very difficult to read (as if blurred). I managed to remove the text layer and OCR it on my own, but it was time consuming - could this be somehow fixed?

This is what it looks like:

![image](https://user-images.githubusercontent.com/2981552/138613022-5c847e34-b277-4062-9184-4174316c75c5.png)

And thanks for a neat script.

**Comment by danieldeng2** [comment]
Fixed in the latest version.
