### ISSUE TITLE
 Uncaught TypeError: Cannot read property 'scrollIntoView' of null

### ISSUE THREAD

**Issue by dowcet** [danieldeng2/perlego-downloader#2]
I am not very familiar with Javascript, etc so please bear with me :) I am in Windows 10 using Chrome 87 which it says is up-to-date and I am testing this tool out with a short book, https://ereader.perlego.com/1/book/2004984/0. 

As soon as I open the Console, I already see two errors:

- Failed to load resource: the server responded with a status of 404 () qA6R4rzoUBvRAjdAGj_qJMJTvQU.js:1 
- Failed to load resource: the server responded with a status of 404 () api.perlego.com/ugc/v2/packaged-highlights?book_id=2004984:1 

When I paste PerlegoContent.js that looks ok, I just get the message `undefined`. Then when I run `printPages(0, 31)` I also see the undefined message, but also the following error:

- Uncaught TypeError: Cannot read property 'scrollIntoView' of null
    at <anonymous>:8:21
    at r (0ca6f96311d46b314229.bundle.js:123)
    0ca6f96311d46b314229.bundle.js:123 
    
 Nothing else seems to happen. Am I doing something wrong?

**Comment by danieldeng2** [comment]
The first two errors have nothing to do with the script.

The typeError is because the script cannot find the relevant page. The script here only works on books that are uploaded as pdfs at the moment. Are you sure that is the cause here?

**Comment by dowcet** [comment]
> The script here only works on books that are uploaded as pdfs at the moment. Are you sure that is the case here?

Ah, that instructions say "ideally" so I didn't think it was a strict requirement. I would suggest clarifying that but will close this for now.
