### ISSUE TITLE
download all epub chapters?

### ISSUE THREAD

**Issue by otichy** [danieldeng2/perlego-downloader#20]
All epubs I have seen at Perlego so far have been divided into chapters that load separately and chapter numbers rather than pages are the last element of the URL (e.g. https://ereader.perlego.com/1/book/1472050/18). Currently, the script only works if you print one chapter at a time (e.g. printPages(18,18)). 

However there can be a large number of short chapters and downloading them separately is really time consuming. Could the script load each chapter and print it automatically?

**Comment by AndroidDevice1** [comment]
How did you manage even chapter wise? When I run the script on an epub file it all loads properly in the browser, but when I seek to save it it shows me a blank page. I'm assuming I can't print to pdf because it's an epub file? How do I save the chapter?

**Comment by otichy** [comment]
> How did you manage even chapter wise? When I run the script on an epub file it all loads properly in the browser, but when I seek to save it it shows me a blank page. I'm assuming I can't print to pdf because it's an epub file? How do I save the chapter?

I think it works the same for epub and PDF, if you only see white page in the print dialogue, maybe you need to wait a bit. For me, something like the recommended 150 pages takes a couple minutes.

**Comment by AndroidDevice1** [comment]
It was the browser. I used Chrome because it was specified. It worked using Brave now.

**Comment by otichy** [comment]
Interesting, it works in Chrome for me (Version 95.0.4638.69 (Official Build) (64-bit) on Win 11)
