### ISSUE TITLE
Pages are layered twice on top of each other in printed PDF.

### ISSUE THREAD

**Issue by antoasis** [danieldeng2/perlego-downloader#22]
I guess it's easier to just show the problem than describe it. Here's a screenshot:
![print from perlego](https://user-images.githubusercontent.com/95924669/145590447-bcaae987-e347-41a0-a7f6-c286f60b5111.png)

Basically, the browser prints every page once, and then prints the same page again over itself with a slight offset - hence every letter appears doubled. I'm not sure if that's an issue of the script itself or the browser/print-to-pdf utility, but as you can see on the screenshot, when the print preview window opens, the text already looks doubled.

Also, see what happens when I try to zoom in/out in the preview window:
![Screenshot from Perlego](https://user-images.githubusercontent.com/95924669/145592580-77884817-c7d9-4e3e-852b-ca34d27e4c48.png)

I must also say that this happens only when I try to print SOME pdf's. It doesn't happen for every file. But for those files that it occurs with, it occurs consistently.

Thanks.

**Comment by antoasis** [comment]
UPDATE: I now understand why this happens. Some books on perlego are scanned bookpages with invisible text overlayed over the scans (so one could search words in the book or select text). When I'm trying to print a PDF, the printing utility makes that invisible text visible, and overlays it over the images of the pages.

It seems that the issue is of the printing utility (not the script). Still dunno how to fix it though. If anyone knows, I'll appreciate help.

**Comment by otichy** [comment]
https://github.com/danieldeng2/perlego-downloader/issues/18

**Comment by danieldeng2** [comment]
Fixed in the latest version.
