### ISSUE TITLE
Can you help me?

### ISSUE THREAD

**Issue by jackyzfy** [danieldeng2/perlego-downloader#3]
function printPages(start, end) {
    document.querySelector("style").remove();
    let printContents = "";
    let i = start;
    function downloadPage() {
        setTimeout(()=>{
            let content = document.querySelector(`div[data-chapterid='${i}']`);
            content.scrollIntoView();
            if (content.querySelector(".pdfplaceholder") == null) {
                printContents += content.innerHTML + "<br>";
                i++;
            }
            if (i <= end) {
                downloadPage();
            }
            if (i == end + 1) {
                document.body.innerHTML = printContents;
                console.log("Reading...");
                setTimeout(()=>{
                    window.print();
                    location.reload();
                }
                , (end - start) * 100);
            }
        }
        , 1000);
    }
    downloadPage();
}
undefined
printPages(1,10)
undefined
090a5a37c4e59168f885.bundle.js:1364 Uncaught TypeError: Cannot read property 'scrollIntoView' of null
    at <anonymous>:8:21
    at r (090a5a37c4e59168f885.bundle.js:1364)
(anonymous) @ VM367:8
r @ 090a5a37c4e59168f885.bundle.js:1364
setTimeout (async)
(anonymous) @ 090a5a37c4e59168f885.bundle.js:1364
downloadPage @ VM367:6
printPages @ VM367:28
(anonymous) @ VM387:1

**Comment by danieldeng2** [comment]
Unfortunately the script currently only works on bools that were uploaded as pdfs. sorry for the late reply

**Comment by jackyzfy** [comment]
> Unfortunately the script currently only works on bools that were uploaded as pdfs. sorry for the late reply

Ok, I finish it after copy and paste all article.
