### ISSUE TITLE
Some pages don't fully load

### ISSUE THREAD

**Issue by noissueshere** [danieldeng2/perlego-downloader#4]
I can run your code on up to 80 pages at a time (I find that more just gets the code stuck on some page after)

The problem is that some of the pages don't fully load under your script. If I view them normally they do.

I also tried to run the code on the specific pages that don't fully load. No better result.

The book is PDF and usually the drawings, schemas and tables don't always load.

Here is the link to a page that causes problems in the book I'm trying to get: .../1/book/1707804/16

**Comment by danieldeng2** [comment]
Seems to be the same issue with #7 , will add the option to choose loading time for each page

**Comment by danieldeng2** [comment]
should be fixed, try with the new pageTime option
