### ISSUE TITLE
NOT WORKING PROPERLY?

### ISSUE THREAD

**Issue by delcaz** [danieldeng2/perlego-downloader#6]
Dear Daniel, 
I am trying to use your script to download a book that I need offline.
Unfortunately, when I execute the script in the console, I see "syntax error" and the print function appears as not defined.
Any ideas of why it can happen?

!
![Capture2705](https://user-images.githubusercontent.com/84895693/119776358-e1c49380-bed5-11eb-8b5f-8728e1fb90c4.JPG)

![Capture2705](https://user-images.githubusercontent.com/84895693/119776419-f86aea80-bed5-11eb-8017-fa84c61a3182.JPG)

**Comment by bulbcult** [comment]
I think for perlego you can only set the start and end page as the same value, like printPage(3,3)
Maybe it's due to there is only one page for that webview :)

**Comment by danieldeng2** [comment]
Sorry if this is a bit late but you seemed to have copied the copyright notice from github as well. try this: https://raw.githubusercontent.com/danieldeng2/perlego-downloader/main/PerlegoContent.js
