### ISSUE TITLE
Front cover doesn't load fully

### ISSUE THREAD

**Issue by Big592** [danieldeng2/perlego-downloader#9]
I tried the old and new code, yet it still not working. It does download correctly, however some of the pages such as the pages with background photo (e.g. front cover, chapter page) do not download properly, the text is downloaded properly but not the background photo. I have tried several numbers e.g. 30000, 100000 etc. and I'm still not getting download correctly.

**Comment by danieldeng2** [comment]
I remember covers not rendering for me before. might be a rendering issue. 

I'll take a look when I have time. If anyone else fond a fix I'll be happy to merge it.

**Comment by ro0sterjam** [comment]
I suggest just removing the print command completely for debugging:

```
function printPages(start, end, pageTime=100) {
    document.querySelector("style").remove();
    let printContents = "";
    let i = start;
    function downloadPage() {
        setTimeout(()=>{
            let content = document.querySelector(`div[data-chapterid='${i}']`);
            content.scrollIntoView();
            if (content.querySelector(".pdfplaceholder") == null) {
                printContents += content.innerHTML + "<br>";
                i++;
            }
            if (i <= end) {
                downloadPage();
            }
            if (i == end + 1) {
                document.body.innerHTML = printContents;
                console.log("Reading...");
                // comment out for testing
                //setTimeout(() => {
                //  window.print();
                //  location.reload();
                //}, (end - start) * pageTime);
            }
        }
        , 1000);
    }
    downloadPage();
}
```

If you run this code, it won't load the print dialogue and you can check the network tab to see if there are any elements which failed to load or something.

**Comment by Big592** [comment]
> I suggest just removing the print command completely for debugging:
> 
> ```
> function printPages(start, end, pageTime=100) {
>     document.querySelector("style").remove();
>     let printContents = "";
>     let i = start;
>     function downloadPage() {
>         setTimeout(()=>{
>             let content = document.querySelector(`div[data-chapterid='${i}']`);
>             content.scrollIntoView();
>             if (content.querySelector(".pdfplaceholder") == null) {
>                 printContents += content.innerHTML + "<br>";
>                 i++;
>             }
>             if (i <= end) {
>                 downloadPage();
>             }
>             if (i == end + 1) {
>                 document.body.innerHTML = printContents;
>                 console.log("Reading...");
>                 // comment out for testing
>                 //setTimeout(() => {
>                 //  window.print();
>                 //  location.reload();
>                 //}, (end - start) * pageTime);
>             }
>         }
>         , 1000);
>     }
>     downloadPage();
> }
> ```
> 
> If you run this code, it won't load the print dialogue and you can check the network tab to see if there are any elements which failed to load or something.
> 
> Then if it's good and ready to print, manually call `window.print()` to print it, and then `location.reload()` after that to reload the page.

Hi, I tried this but it didn't work. However I did try another method. Instead of using Chrome, I used Firefox and it managed to load up. I think the issue is probably Chrome itself.
